// Code generated by "stringer -type=MAState -linecomment"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MAStateAbove-0]
	_ = x[MAStateBelow-1]
	_ = x[MAStateEqual-2]
}

const _MAState_name = "abovebelowequal"

var _MAState_index = [...]uint8{0, 5, 10, 15}

func (i MAState) String() string {
	if i < 0 || i >= MAState(len(_MAState_index)-1) {
		return "MAState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MAState_name[_MAState_index[i]:_MAState_index[i+1]]
}
