// Code generated by "stringer -type=SymbolStatus -linecomment"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymbolStatusTrading-0]
	_ = x[SymbolStatusBreaking-1]
}

const _SymbolStatus_name = "TRADINGBREAKING"

var _SymbolStatus_index = [...]uint8{0, 7, 15}

func (i SymbolStatus) String() string {
	if i < 0 || i >= SymbolStatus(len(_SymbolStatus_index)-1) {
		return "SymbolStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SymbolStatus_name[_SymbolStatus_index[i]:_SymbolStatus_index[i+1]]
}
